### ISSUE TITLE
Can't seem to enable local API on Nicehash Miner.

### ISSUE THREAD

**Issue by old-square-eyes** [MesserschmittX/hacs-nicehash-excavator#3]
What if you're using Nicehash Miner (as opposed to Quickminer or CLI)?

**Comment by old-square-eyes** [comment]
![image](https://user-images.githubusercontent.com/25760491/221385857-52dd7353-16e0-4e57-b44d-f677d806b4c8.png)

Or

![image](https://user-images.githubusercontent.com/25760491/221385872-7c3e8889-3b7f-4b00-84ba-69c92d6bc0b9.png)

From here: https://www.nicehash.com/blog/post/nbminer-command-lines-(extra-launch-parameters)

Don't wokFrom Advanced >Extra ommands. Nor does adding command lind params to the Windows launching shortcut.

**Comment by old-square-eyes** [comment]
"Miner name is the name of your mining rig" is that Worker name? I can't see "Miner name" anywhere.

I can ping my miner machine from Home Assistant and I have an inbound firewall rule on 18000. I can't figure this out.

**Comment by NeonGrayX** [comment]
I just tested it, you need to use only one - instead of the -- for the wi and wp commands then it will work. Miner name is just the display name in Homeassistant.

**Comment by old-square-eyes** [comment]
Thanks!
