### ISSUE TITLE
Start/Stop Miner

### ISSUE THREAD

**Issue by old-square-eyes** [MesserschmittX/hacs-nicehash-excavator#4]
Start/Stop miner. I'd love to be able to start and stop my miner based on automation (in my case surplus solar energy exporting to the grid). I have that trigger but can't figure how to do the post described below...

![image](https://user-images.githubusercontent.com/25760491/221402265-4592db2c-721c-4f93-ae83-45313e56b4d2.png)

https://www.nicehash.com/docs/rest

**Comment by NeonGrayX** [comment]
This is out of scope for this integration. This integration is only for monitioring and it is doing that by only accessing the local Excavator API. What you want is part of the online API of Nicehash. You can either solve this by making a [REST switch](https://www.home-assistant.io/integrations/switch.rest/) to call this endpoint, or try to request this as a feautre from an integration where the Nicehash API is used like [NiceHash Home Assistant Integration
](https://github.com/brianberg/ha-nicehash)
